### ISSUE TITLE
can't scp or use git over ssh from remote sites

### ISSUE THREAD

**Issue by sbutcher** [jade-hpc-gpu/jade-hpc-gpu.github.io#15]
Using JADE I can't scp from a remote system, and i can't perform git operations from a repo using the preferred git over ssh (to use key based auth)
this heavily impacts workflow.

**Comment by martinjhnhadley** [comment]
@sbutcher does this remain an issue?

**Comment by sbutcher** [comment]
@martinjhnhadley yes, i've seen no indication of any progress on it - does it need raising separately on hartree service now?

**Comment by LiamATOS** [comment]
Can you try using HTTPS for GIT, the DGX Nodes do not have direct internet access

**Comment by sbutcher** [comment]
@LiamATOS git over HTTPS requires username and password for each git operation, and if you use 2FA on github it is even more tedious.
This totally disrupts workflow, RSEs and researchers will need to be able to use git commands seamlessly using key based auth to use the service (as do the other tier2 services).

**Comment by LiamATOS** [comment]
Is it just github.com? STFC will only amend the firewall for specific website's for security reasons?

Thanks

Liam

**Comment by sbutcher** [comment]
we also heavily use github.research.its.qmul.ac.uk our onsite github enterpise. i expect other sites will have similar. it seems a strange restriction because other T2 aren't affected?

**Comment by LiamATOS** [comment]
Requests to STFC networks have gone in, need to check and test.

**Comment by LiamATOS** [comment]
This should now be resolved, please check

**Comment by sbutcher** [comment]
Hi
I still cannot access github.research.its.qmul.ac.uk on git/ssh protocol (port 22 and 443 required)
github.com does work fine with keys but we also need the QMUL one please.
thanks

**Comment by we-taper** [comment]
Hi
I confirm that `bitbucket` via ssh isn't available as well. It looks like `via HTTPS` is general working, though it is not a good idea to enter my passwords every time.

Hope it could be done in the future.

**Comment by we-taper** [comment]
Dear all,

Now I think that git with ssh over https is not working as well. For example the following works on my Mac:
`git clone ssh://git@altssh.bitbucket.org:443/me/xxx.git`

But it gives on the jade:

    ssh: connect to host altssh.bitbucket.org port 443: Network is unreachable
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by agniszczotka** [comment]
Issue remains. I use  git@cmiclab.cs.ucl.ac.uk which is internal gitlab. How to set up git connection?

**Comment by twinkarma** [comment]
Is this still an issue?

**Comment by agniszczotka** [comment]
Yes. I generated my public key with Jade account and registered with my repository account, which usually allows me access to [git@cmiclab.cs.ucl.ac.uk](mailto:git@cmiclab.cs.ucl.ac.uk) from any machine. It did not work for Jade.
Error is:
`ssh: connect to host cmiclab.cs.ucl.ac.uk port 22: Connection timed out`
`fatal: Could not read from remote repository.
`

**Comment by martinengelcke** [comment]
I also usually access Github repos via ssh. This worked before but then suddenly stopped working for me on Jade last week. Access via https works fine.

It is possible that something has gone wrong with my ssh configuration but I cannot spot anything.

**Comment by TreeLLi** [comment]
I also have the problem of connecting Git via SSH and solved by switching to HTTPS. It seems that JADE administrator has closed the port for ssh according to the [post](https://stfc.service-now.com/hartreecentre?id=kb_article&sys_id=4188638ddb5a5f002effbae76896193f) from Hartree. Besides, if you are also considering HTTPS solution, you may want to have a look at this #123  regarding setting proxy for https connection working.
